[package]
name = "satsnet-rpc-json"
version = "0.19.6"
authors = ["Jacky Chen <softwarecheng@gmail.com>"]
license = "CC0-1.0"
homepage = "https://github.com/sat20-labs/rust-satsnet-rpc/"
repository = "https://github.com/sat20-labs/rust-satsnet-rpc/"
description = "JSON-enabled type structs for bitcoincore-rpc crate."
keywords = [ "crypto", "bitcoin", "bitcoin-core", "rpc" ]
readme = "README.md"
edition = "2021"
rust-version = "1.56.1"

[lib]
name = "bitcoincore_rpc_json"
path = "src/lib.rs"

[features]
default = ["rand"]
rand = ["bitcoin/rand-std"]
bitcoin_with_satsnet = ["rand"]

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

# bitcoin = { package = "satsnet", path = "/Users/chenwenjie/test/rust/rust-satsnet/satsnet", version = "0.32.14", features = ["serde"] }
bitcoin = { package = "satsnet", version = "0.32.16", features = ["serde"] }